#!/bin/bash
#
# https://github.com/mattias-ohlsson/topnmap

set -e

self=$(basename "$0")
self_version=0.7
cache_dir_path="$HOME/.cache/$self"

# Parse options
TEMP=`getopt -o h -l help,version,assumeyes -n $self -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$TEMP"

while true ; do
	case "$1" in
		-h|--help)
			cat <<- EOF
			Usage: $self [options] PROTOCOL TARGET...
			
			Options:
			  --version         print version information and exit
			  -h, --help        show this help message and exit

			Protocol list:
			  tcp
			  udp
			EOF
			shift
			exit ;;
		--version)
			echo $self_version; shift ; exit ;;
		--) shift ; break ;;
		*) echo "Internal error!" ; exit 1 ;;
	esac
done

protocol=$1
shift

if [ "$protocol" != "tcp" ] && [ "$protocol" != "udp" ]; then
	echo "usage: $self --help"
	exit 1
fi

target=$@

if [ -z "$target" ]; then
	echo "usage: $self --help"
	exit 1
fi

command -v nmap >/dev/null || { echo "$self: nmap: command not found"; \
 exit 1; }

if [ ! -f "/usr/share/nmap/nmap-services" ]; then
	echo "$self: /usr/share/nmap/nmap-services: No such file"
	exit 1
fi

target_signature=$(md5sum <<< $target | cut -d" " -f1)

if [ ! -d "$cache_dir_path" ]; then
	echo "$self: creating directory $cache_dir_path"
	mkdir -p "$cache_dir_path"	
fi

# Create port list
if [ ! -f "$cache_dir_path/topnmap-$protocol-sorted.list" ]; then
	echo "$self: generating $protocol list"

	cat /usr/share/nmap/nmap-services | grep -v ^# | grep -e $'^.*[^\t]\t[0-9]*/'$protocol$'\t.*' | \
	 sort -rk3 | cut -f2 | cut -d/ -f1 > "$cache_dir_path/topnmap-$protocol-sorted.list"

	for p in {1..65536}; do
		grep -q ^$p$ "$cache_dir_path/topnmap-$protocol-sorted.list" || \
		 echo $p >> "$cache_dir_path/topnmap-$protocol-sorted.list"
	done
fi

for i in {1..65536}; do

	if [ -f "$cache_dir_path/$target_signature-$protocol-$i" ]; then
		continue
	fi

	echo "$self: $target_signature stage: $i"

	nmap_parameters=(-Pn)
	nmap_parameters+=(-n)

	if [ "$protocol" == "udp" ]; then
		nmap_parameters+=(-sU)
	else
		nmap_parameters+=(-sS)
	fi

	port=$(sed -n "${i}p" "$cache_dir_path/topnmap-$protocol-sorted.list")

	nmap_parameters+=(-p $port)

	nmap_parameters+=(-oX topnmap-$target_signature-$protocol-$port.xml)

	nmap_parameters+=($target)

	nmap ${nmap_parameters[@]}

	touch "$cache_dir_path/$target_signature-$protocol-$i"
done
